//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AVGpacketsCountTenSecond
    {
        public int TimePeriod { get; set; }
        public Nullable<int> packetCount { get; set; }
        public Nullable<int> counterOfSyn { get; set; }
        public Nullable<int> counterOfAck { get; set; }
        public Nullable<int> counterOfPa { get; set; }
        public Nullable<int> counterOfR { get; set; }
        public Nullable<int> counterOfRA { get; set; }
        public Nullable<int> counterOfFin { get; set; }
        public Nullable<int> packetsTotalSize { get; set; }
    }
}
