//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebConsole.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow
    {
        public long FlowID { get; set; }
        public long UnixStartTimeMillisec { get; set; }
        public long UnixEndTimeMillisec { get; set; }
        public long Time { get; set; }
        public string Day { get; set; }
        public int TimePeriod { get; set; }
        public string srcIpAddr { get; set; }
        public string dstIpAddr { get; set; }
        public string Service { get; set; }
        public int srcPort { get; set; }
        public int dstPort { get; set; }
        public int counterOfPackets { get; set; }
        public int counterOfSyn { get; set; }
        public int counterOfPa { get; set; }
        public int counterOfR { get; set; }
        public int counterOfRA { get; set; }
        public int counterOfFin { get; set; }
        public int packetsTotalSize { get; set; }
    }
}
